In [33]:
%load_ext autoreload
%autoreload 2

In [34]:
import numpy as np
from pupil_metrics import *

In [54]:
a = np.array([[1,2,3], [1,3,4], [3,4,5], [5,6,7]])
b = np.array([1,1,1,1,1,1])

In [58]:
a[:, 2] - a[:, 0]

array([2, 3, 2, 2])

In [55]:
std_pupil_size(b)

array([0.])

In [47]:
x1 = np.arange(9.0).reshape((3, 3))
np.argmax(x1, axis=1) - 2

array([0, 0, 0])

In [42]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [45]:
x1 - x2

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])